color0 #0a1c48
color1 #fd4663
color2 #6289e9
color3 #8166ff
color4 #b94de6
color5 #8fabef
color6 #a38fef
color7 #f2f2f3
color8 #5f646f
color9 #fd4663
color10 #6289e9
color11 #8166ff
color12 #b94de6
color13 #8fabef
color14 #a38fef
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #071536
background            #071536
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #0a1c48
active_border_color   #6289e9
inactive_border_color #0a1c48
url_color             #6289e9

active_tab_foreground   #181c25
active_tab_background   #6289e9
inactive_tab_foreground #afb1b6
inactive_tab_background #0a1c48
cursor_trail_color      #afb1b6
