color0 #37281b
color1 #b47a47
color2 #e4a467
color3 #5c90d6
color4 #9bd85a
color5 #ecbe93
color6 #96b9e9
color7 #f3f2f2
color8 #716961
color9 #b47a47
color10 #e4a467
color11 #5c90d6
color12 #9bd85a
color13 #ecbe93
color14 #96b9e9
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291e14
background            #291e14
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #37281b
active_border_color   #e4a467
inactive_border_color #37281b
url_color             #e4a467

active_tab_foreground   #251e18
active_tab_background   #e4a467
inactive_tab_foreground #b6b2af
inactive_tab_background #37281b
cursor_trail_color      #b6b2af
