color0 #282c25
color1 #fd4663
color2 #99e467
color3 #5cd668
color4 #66cca3
color5 #b6ec93
color6 #96e99e
color7 #f2f3f2
color8 #646d5f
color9 #fd4663
color10 #99e467
color11 #5cd668
color12 #66cca3
color13 #b6ec93
color14 #96e99e
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1e211c
background            #1e211c
foreground            #f2f3f2
selection_foreground  #b2b6af
selection_background  #282c25
active_border_color   #99e467
inactive_border_color #282c25
url_color             #99e467

active_tab_foreground   #1d2518
active_tab_background   #99e467
inactive_tab_foreground #b2b6af
inactive_tab_background #282c25
cursor_trail_color      #b2b6af
