# Key Bindings
# mod keys name: super,ctrl,alt,shift,none

# System
bind=CTRL+SHIFT,end,quit #"mango quit"
bind=SUPER+SHIFT,c,killclient #"kill client"
bind=SUPER,r,reload_config #"reload mango config"

# Noctalia
bind=NONE,Print,spawn, noctalia msg screenshot-region #"screenshot-region"
# TODO more screenshot binds fullscreen, quick, editor
bind=SUPER,space,spawn,noctalia msg panel-toggle launcher #"noctalia launcher"
bind=SUPER,s,spawn,noctalia msg panel-toggle control-center #"noctalia control center"
bind=none,XF86Tools,spawn,noctalia msg settings-toggle #"noctalia settings"

# Noctalia Plugins
# TODO setup timer, calculator, speedtest, powermanager, battery, bazzar search, screen toolkit,
bind=SUPER+SHIFT,u,spawn,noctalia msg panel-toggle aristides/udiskie:manager #"udiskie"
bind=SUPER+SHIFT,m,spawn,noctalia msg panel-toggle vn1k/cursor:manager #"cursor manager"
bind=SUPER+SHIFT,Escape,spawn,noctalia msg panel-toggle tordex/processes:panel -mem #"task manager"
bind=none,XF86Keyboard,spawn,noctalia msg panel-toggle blackbartblues/keymap:panel #"keymaps"
bind=none,XF86Favorites,spawn,noctalia msg panel-toggle tordex/system-updater:panel #"system updater"
bind=none,XF86Display,spawn,noctalia msg panel-toggle prponkshe/mango-displays:panel #"mango displays"

# Media keys
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up #"up volume"
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down #"down volume"
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute #"mute volume"
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up #"up brightness"
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down #"down brightness"

# Applications
bind=SUPER,Return,spawn,kitty #"kitty terminal"

# Scratchpad Applications
bind=SUPER,F1,toggle_named_scratchpad,org.keepassxc.KeePassXC,none,keepassxc #"kepassxc"
bind=SUPER,F2,toggle_named_scratchpad,superproductivity,none,superproductivity #"superproductivity"
bind=SUPER,Escape,toggle_named_scratchpad,none,kitty-scratch,kitty -T kitty-scratch -e zsh #"kitty terminal scratchpad"

# Windows and Tags
bind=SUPER,h,focusdir,left #"focus left"
bind=SUPER,l,focusdir,right #"focus right"
bind=SUPER,j,focusdir,down #"focus down"
bind=SUPER,k,focusdir,up #"focus up"
bind=ALT,Tab,overcircle,next #"alt tab"

#bind=SUPER,Tab,focuslast
bind=SUPER+SHIFT,h,exchange_client,left #"move window to the left"
bind=SUPER+SHIFT,l,exchange_client,right #"move window to the right"
bind=SUPER,f,togglefullscreen #"toggle fullscreen"
bind=SUPER+SHIFT,space,togglefloating #"toggle floating window"

# Scroller layout 
bind=SUPER,e,set_proportion,1.0 #"set set proportion to 1.0"
bind=SUPER,x,switch_proportion_preset #"cycle proportion presets"

# tag switch
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# move client to tag
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Monitors
bind=SUPER,q,focusmon,right #"change monitor focus"
bind=SUPER+SHIFT,q,tagmon,right #"change window monitor"

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove #"move window with mouse"
mousebind=SUPER,btn_right,moveresize,curresize #"resize window with mouse"
axisbind=SUPER,UP,viewtoleft_have_client #"focus workspace to the left"
axisbind=SUPER,DOWN,viewtoright_have_client  #"focus workspace to the right"

